// Static seed data shown in the demo workspace — no real client data ever exposed

export const DEMO_CONTACTS = [
  {
    id: "demo-contact-1",
    name: "Sarah Thompson",
    email: "sarah.t@example.com",
    phone: "+44 7700 900001",
    company: "Thompson Properties",
    lead_type: "landlord",
    status: "qualified",
    source: "referral",
    notes: "Owns 4 HMOs in Manchester. Looking for full management.",
    created_at: "2024-11-15T10:00:00Z",
  },
  {
    id: "demo-contact-2",
    name: "Marcus Webb",
    email: "m.webb@capitalgrowth.co.uk",
    phone: "+44 7700 900002",
    company: "Capital Growth Investments",
    lead_type: "investor",
    status: "proposal_sent",
    source: "website",
    notes: "Interested in 6–8% yields. Has £500k to deploy.",
    created_at: "2024-11-20T09:30:00Z",
  },
  {
    id: "demo-contact-3",
    name: "Priya Patel",
    email: "priya@patelestates.com",
    phone: "+44 7700 900003",
    company: "Patel Estates",
    lead_type: "landlord",
    status: "contacted",
    source: "cold_outreach",
    notes: "2 single-lets in Birmingham. Follow up next week.",
    created_at: "2024-12-01T14:00:00Z",
  },
  {
    id: "demo-contact-4",
    name: "James Hartley",
    email: "james.h@hartleybuild.co.uk",
    phone: "+44 7700 900004",
    company: "Hartley Build",
    lead_type: "maintenance_client",
    status: "closed_won",
    source: "referral",
    notes: "Ongoing maintenance contract. Reliable payer.",
    created_at: "2024-10-10T08:00:00Z",
  },
  {
    id: "demo-contact-5",
    name: "Olivia Chen",
    email: "olivia@futurestacktech.io",
    phone: "+44 7700 900005",
    company: "FutureStack Tech",
    lead_type: "ai_automation_prospect",
    status: "lead",
    source: "form_ai_automation",
    notes: "Wants AI workflow automation for their property ops team.",
    created_at: "2024-12-10T11:00:00Z",
  },
];

export const DEMO_DEALS = [
  {
    id: "demo-deal-1",
    name: "Thompson HMO Portfolio",
    contact_id: "demo-contact-1",
    stage: "proposal",
    value: 18000,
    currency: "GBP",
    probability: 70,
    expected_close: "2025-02-28",
    notes: "Full management for 4 HMOs. £1,500/mo recurring.",
  },
  {
    id: "demo-deal-2",
    name: "Webb Investment Package",
    contact_id: "demo-contact-2",
    stage: "negotiation",
    value: 500000,
    currency: "GBP",
    probability: 55,
    expected_close: "2025-03-15",
    notes: "Sourcing + management deal. Commission: 2% of acquisition.",
  },
  {
    id: "demo-deal-3",
    name: "Hartley Maintenance Contract",
    contact_id: "demo-contact-4",
    stage: "closed_won",
    value: 24000,
    currency: "GBP",
    probability: 100,
    expected_close: "2024-12-01",
    notes: "Annual contract signed. Direct debit active.",
  },
];

export const DEMO_TASKS = [
  {
    id: "demo-task-1",
    title: "Follow up Sarah Thompson on HMO proposal",
    task_type: "follow_up",
    status: "todo",
    priority: "high",
    due_date: "2025-01-20",
  },
  {
    id: "demo-task-2",
    title: "Send investment pack to Marcus Webb",
    task_type: "admin",
    status: "in_progress",
    priority: "high",
    due_date: "2025-01-18",
  },
  {
    id: "demo-task-3",
    title: "Schedule site visit — Patel Estates Birmingham",
    task_type: "meeting",
    status: "todo",
    priority: "medium",
    due_date: "2025-01-25",
  },
  {
    id: "demo-task-4",
    title: "Monthly maintenance report — Hartley Build",
    task_type: "admin",
    status: "completed",
    priority: "low",
    due_date: "2025-01-10",
  },
  {
    id: "demo-task-5",
    title: "AI automation discovery call — FutureStack Tech",
    task_type: "call",
    status: "todo",
    priority: "urgent",
    due_date: "2025-01-17",
  },
];

export const DEMO_INBOX = [
  {
    id: "demo-conv-1",
    platform: "email",
    contact_name: "Sarah Thompson",
    subject: "Re: HMO management proposal",
    latest_message: "Thanks for the detailed proposal. I'd like to discuss the fee structure before signing. Can we schedule a call this week?",
    status: "open",
    priority: "high",
    is_read: false,
    created_at: "2025-01-14T09:15:00Z",
  },
  {
    id: "demo-conv-2",
    platform: "whatsapp",
    contact_name: "James Hartley",
    subject: "Maintenance request — Unit 3B",
    latest_message: "Hi, boiler's playing up again at 3B. Tenant's complained twice. Can you get someone out this week?",
    status: "open",
    priority: "urgent",
    is_read: false,
    created_at: "2025-01-14T07:45:00Z",
  },
  {
    id: "demo-conv-3",
    platform: "linkedin",
    contact_name: "Marcus Webb",
    subject: "Investment opportunity follow-up",
    latest_message: "Appreciate you sending the deal pack. The Salford opportunity looks interesting — what's the projected yield after fees?",
    status: "waiting",
    priority: "high",
    is_read: true,
    created_at: "2025-01-13T16:00:00Z",
  },
];

export const DEMO_KPI = {
  active_leads:     12,
  open_deals:       5,
  total_pipeline:   "£742,000",
  tasks_due_today:  3,
  inbox_unread:     7,
  monthly_revenue:  "£38,400",
  conversion_rate:  "34%",
  avg_deal_days:    22,
};

export const DEMO_AUTOMATION_FEED = [
  { event: "new_contact",    label: "New lead captured",         time: "2 min ago",  status: "success" },
  { event: "hot_lead",       label: "AI scored hot lead",        time: "14 min ago", status: "success" },
  { event: "task_created",   label: "Follow-up task auto-created", time: "1 hr ago", status: "success" },
  { event: "message_received", label: "Inbox message routed",    time: "3 hr ago",  status: "success" },
  { event: "deal_updated",   label: "Deal stage updated",        time: "Yesterday",  status: "success" },
];

export const DEMO_PACKAGES = [
  {
    id: "starter",
    name: "Starter OS",
    price: "£997",
    period: "one-time setup + £197/mo",
    description: "Perfect for landlords and small agencies ready to get organised.",
    features: [
      "CRM for up to 50 contacts",
      "Task & calendar management",
      "Inbox (email + WhatsApp)",
      "Basic automation (5 workflows)",
      "1 onboarding session",
    ],
    highlight: false,
  },
  {
    id: "growth",
    name: "Growth OS",
    price: "£2,497",
    period: "one-time setup + £397/mo",
    description: "For growing agencies managing multiple landlords and deal pipelines.",
    features: [
      "Everything in Starter",
      "Unlimited CRM contacts",
      "Deal tracker + pipeline",
      "Advanced automations (25 workflows)",
      "Finance & project management",
      "Priority support",
    ],
    highlight: true,
  },
  {
    id: "automation",
    name: "Automation OS",
    price: "£4,997",
    period: "one-time setup + £697/mo",
    description: "Full AI-powered automation stack for high-volume operations.",
    features: [
      "Everything in Growth",
      "AI lead qualification",
      "n8n workflow builder",
      "Custom integrations (CRMs, portals)",
      "White-label option",
      "Dedicated account manager",
    ],
    highlight: false,
  },
  {
    id: "custom",
    name: "Custom AI OS",
    price: "From £9,997",
    period: "bespoke pricing",
    description: "Fully custom AI operating system built around your business.",
    features: [
      "Everything in Automation",
      "Custom AI models & prompts",
      "Bespoke workflow design",
      "API & data integrations",
      "Staff training & rollout",
      "Ongoing development retainer",
    ],
    highlight: false,
  },
];
