// Static seed data shown in the demo workspace — no real client data ever exposed

export const DEMO_CONTACTS = [
  {
    id: "demo-contact-1",
    name: "Sarah Thompson",
    email: "sarah.t@example.com",
    phone: "+44 7700 900001",
    company: "Thompson Properties",
    lead_type: "landlord",
    status: "qualified",
    source: "referral",
    notes: "Owns 4 HMOs in Manchester. Looking for full management.",
    ai_score: "hot" as const,
    ai_rank: 1,
    bottleneck: "Too many manual tasks",
    last_activity: "2 hours ago",
    stage: "qualified",
    value: "£18,000",
    activity_log: [
      { type: "email", label: "Opened proposal email", time: "2 hours ago" },
      { type: "call", label: "Discovery call completed", time: "3 days ago" },
      { type: "note", label: "Note added: 4 HMOs in Manchester", time: "5 days ago" },
      { type: "lead", label: "Contact created via referral", time: "2 weeks ago" },
    ],
    created_at: "2024-11-15T10:00:00Z",
  },
  {
    id: "demo-contact-2",
    name: "Marcus Webb",
    email: "m.webb@capitalgrowth.co.uk",
    phone: "+44 7700 900002",
    company: "Capital Growth Investments",
    lead_type: "investor",
    status: "proposal_sent",
    source: "website",
    notes: "Interested in 6–8% yields. Has £500k to deploy.",
    ai_score: "hot" as const,
    ai_rank: 2,
    bottleneck: "Finance visibility",
    last_activity: "1 day ago",
    stage: "proposal_sent",
    value: "£500,000",
    activity_log: [
      { type: "email", label: "Replied to investment pack", time: "1 day ago" },
      { type: "deal", label: "Deal moved to negotiation", time: "3 days ago" },
      { type: "email", label: "Investment pack sent", time: "5 days ago" },
      { type: "lead", label: "Signed up via website form", time: "3 weeks ago" },
    ],
    created_at: "2024-11-20T09:30:00Z",
  },
  {
    id: "demo-contact-3",
    name: "Priya Patel",
    email: "priya@patelestates.com",
    phone: "+44 7700 900003",
    company: "Patel Estates",
    lead_type: "landlord",
    status: "contacted",
    source: "cold_outreach",
    notes: "2 single-lets in Birmingham. Follow up next week.",
    ai_score: "warm" as const,
    ai_rank: 3,
    bottleneck: "Client management",
    last_activity: "4 days ago",
    stage: "contacted",
    value: "£6,000",
    activity_log: [
      { type: "instagram", label: "Responded to Instagram DM", time: "4 days ago" },
      { type: "outreach", label: "Cold outreach sent via Instagram", time: "1 week ago" },
      { type: "lead", label: "Contact created", time: "2 weeks ago" },
    ],
    created_at: "2024-12-01T14:00:00Z",
  },
  {
    id: "demo-contact-4",
    name: "James Hartley",
    email: "james.h@hartleybuild.co.uk",
    phone: "+44 7700 900004",
    company: "Hartley Build",
    lead_type: "maintenance_client",
    status: "closed_won",
    source: "referral",
    notes: "Ongoing maintenance contract. Reliable payer.",
    ai_score: "warm" as const,
    ai_rank: 4,
    bottleneck: "Project tracking",
    last_activity: "6 hours ago",
    stage: "closed_won",
    value: "£24,000",
    activity_log: [
      { type: "whatsapp", label: "WhatsApp: boiler issue Unit 3B", time: "6 hours ago" },
      { type: "payment", label: "Monthly payment received £2,000", time: "5 days ago" },
      { type: "task", label: "Site visit scheduled Unit 3B", time: "1 week ago" },
      { type: "contract", label: "Annual contract signed", time: "3 months ago" },
    ],
    created_at: "2024-10-10T08:00:00Z",
  },
  {
    id: "demo-contact-5",
    name: "Olivia Chen",
    email: "olivia@futurestacktech.io",
    phone: "+44 7700 900005",
    company: "FutureStack Tech",
    lead_type: "ai_automation_prospect",
    status: "lead",
    source: "form_ai_automation",
    notes: "Wants AI workflow automation for their property ops team.",
    ai_score: "cold" as const,
    ai_rank: 5,
    bottleneck: "Scaling operations",
    last_activity: "3 days ago",
    stage: "lead",
    value: "£8,000",
    activity_log: [
      { type: "call", label: "AI discovery call booked", time: "3 days ago" },
      { type: "form", label: "Submitted AI automation enquiry form", time: "1 week ago" },
    ],
    created_at: "2024-12-10T11:00:00Z",
  },
  {
    id: "demo-contact-6",
    name: "Daniel Osei",
    email: "d.osei@oseigroup.co.uk",
    phone: "+44 7700 900006",
    company: "Osei Group",
    lead_type: "investor",
    status: "new",
    source: "linkedin",
    notes: "New build sourcing in London and West Midlands. Large budget.",
    ai_score: "warm" as const,
    ai_rank: 6,
    bottleneck: "Lead follow-up",
    last_activity: "Yesterday",
    stage: "new",
    value: "£250,000",
    activity_log: [
      { type: "whatsapp", label: "Initial WhatsApp conversation", time: "Yesterday" },
      { type: "linkedin", label: "Connected on LinkedIn", time: "3 days ago" },
      { type: "lead", label: "Contact created via LinkedIn", time: "5 days ago" },
    ],
    created_at: "2025-01-08T12:00:00Z",
  },
];

export const DEMO_PROJECTS = [
  {
    id: "demo-project-1",
    name: "Thompson HMO Portfolio",
    type: "deal" as const,
    contact_name: "Sarah Thompson",
    contact_id: "demo-contact-1",
    stage: "proposal",
    value: 18000,
    currency: "GBP",
    probability: 70,
    expected_close: "2025-05-31",
    description: "Full management for 4 HMOs in Manchester. £1,500/mo recurring management fee. Proposal sent — awaiting sign-off on fee structure.",
    tasks_count: 3,
    files_count: 2,
    cost_in: null,
    cost_out: null,
    profit: null,
    progress: 70,
    next_action: "Follow up on revised fee structure — Sarah opened proposal 3x this week",
    contractor: null,
    status: "active" as const,
  },
  {
    id: "demo-project-2",
    name: "Webb Investment Acquisition",
    type: "deal" as const,
    contact_name: "Marcus Webb",
    contact_id: "demo-contact-2",
    stage: "negotiation",
    value: 500000,
    currency: "GBP",
    probability: 55,
    expected_close: "2025-06-15",
    description: "Sourcing + management deal. Commission: 2% of acquisition value. Marcus has £500k to deploy — focused on Salford opportunity.",
    tasks_count: 4,
    files_count: 5,
    cost_in: null,
    cost_out: null,
    profit: null,
    progress: 55,
    next_action: "Send Salford yield breakdown — Marcus asked about projected yield after fees",
    contractor: null,
    status: "at_risk" as const,
  },
  {
    id: "demo-project-3",
    name: "Hartley Refurb — Unit 3B",
    type: "project" as const,
    contact_name: "James Hartley",
    contact_id: "demo-contact-4",
    stage: "in_progress",
    value: 8400,
    currency: "GBP",
    probability: 100,
    expected_close: "2025-06-01",
    description: "Full refurbishment of Unit 3B. New kitchen, bathroom re-tile, replaster throughout. Boiler replacement in progress.",
    tasks_count: 5,
    files_count: 8,
    cost_in: 8400,
    cost_out: 6200,
    profit: 2200,
    progress: 65,
    next_action: "Resolve boiler issue — tenant complaint raised today. Book engineer this week.",
    contractor: "M&E Contractors Ltd",
    status: "active" as const,
  },
  {
    id: "demo-project-4",
    name: "Osei Group — New Build Sourcing",
    type: "deal" as const,
    contact_name: "Daniel Osei",
    contact_id: "demo-contact-6",
    stage: "discovery",
    value: 250000,
    currency: "GBP",
    probability: 30,
    expected_close: "2025-07-31",
    description: "New build sourcing in London and West Midlands. Initial conversation promising — needs qualified location criteria and budget breakdown.",
    tasks_count: 2,
    files_count: 1,
    cost_in: null,
    cost_out: null,
    profit: null,
    progress: 30,
    next_action: "Schedule discovery call — clarify location preference and yield expectations",
    contractor: null,
    status: "active" as const,
  },
];

export const DEMO_DEALS = [
  {
    id: "demo-deal-1",
    name: "Thompson HMO Portfolio",
    contact_id: "demo-contact-1",
    stage: "proposal",
    value: 18000,
    currency: "GBP",
    probability: 70,
    expected_close: "2025-05-31",
    notes: "Full management for 4 HMOs. £1,500/mo recurring.",
  },
  {
    id: "demo-deal-2",
    name: "Webb Investment Package",
    contact_id: "demo-contact-2",
    stage: "negotiation",
    value: 500000,
    currency: "GBP",
    probability: 55,
    expected_close: "2025-06-15",
    notes: "Sourcing + management deal. Commission: 2% of acquisition.",
  },
  {
    id: "demo-deal-3",
    name: "Hartley Maintenance Contract",
    contact_id: "demo-contact-4",
    stage: "closed_won",
    value: 24000,
    currency: "GBP",
    probability: 100,
    expected_close: "2024-12-01",
    notes: "Annual contract signed. Direct debit active.",
  },
];

export const DEMO_FINANCE = {
  summary: {
    revenue: "£38,400",
    expenses: "£14,200",
    net: "£24,200",
    cashflow: "+£8,100",
  },
  monthly: [
    { month: "Jan", revenue: 28000, expenses: 10200 },
    { month: "Feb", revenue: 30500, expenses: 11400 },
    { month: "Mar", revenue: 32000, expenses: 12800 },
    { month: "Apr", revenue: 35200, expenses: 13100 },
    { month: "May", revenue: 36800, expenses: 13700 },
    { month: "Jun", revenue: 38400, expenses: 14200 },
  ],
  categories: [
    { name: "Management Fees",        type: "revenue",  amount: 18400, trend: "+12%"    },
    { name: "Project Income",         type: "revenue",  amount: 12000, trend: "+5%"     },
    { name: "Consulting / Setup",     type: "revenue",  amount: 8000,  trend: "new"     },
    { name: "Staff Costs",            type: "expense",  amount: 5200,  trend: "+3%"     },
    { name: "Software Subscriptions", type: "expense",  amount: 890,   trend: "+£120"   },
    { name: "Marketing / Content",    type: "expense",  amount: 1400,  trend: "-8%"     },
    { name: "Contractor Payments",    type: "expense",  amount: 4200,  trend: "+15%"    },
    { name: "Office / Admin",         type: "expense",  amount: 760,   trend: "stable"  },
    { name: "Project Costs",          type: "expense",  amount: 1750,  trend: "variable"},
  ],
  subscriptions: [
    { name: "Braxton OS",        cost: 397, billing: "monthly"   },
    { name: "Google Workspace",  cost: 48,  billing: "monthly"   },
    { name: "Xero",              cost: 32,  billing: "monthly"   },
    { name: "n8n Cloud",         cost: 24,  billing: "monthly"   },
    { name: "WhatsApp Business", cost: 0,   billing: "free tier" },
  ],
};

export const DEMO_INBOX_THREADS = [
  {
    id: "demo-thread-1",
    platform: "email",
    contact_name: "Sarah Thompson",
    contact_id: "demo-contact-1",
    subject: "Re: HMO management proposal",
    status: "open",
    priority: "high",
    is_read: false,
    created_at: "2025-05-27T09:15:00Z",
    ai_summary: "Sarah has reviewed the proposal and wants to discuss the fee structure. She has opened the proposal 3 times this week — high intent signal.",
    ai_next_action: "Reply confirming availability for a call this week. Offer revised fee structure at £1,400/mo for early commitment.",
    messages: [
      { id: "m1a", direction: "out" as const, body: "Hi Sarah, please find attached our full HMO management proposal for your 4 properties in Manchester. The package includes full tenant management, maintenance coordination, and monthly reporting.", sender_name: "Braxton OS Team", time: "3 days ago" },
      { id: "m1b", direction: "in" as const, body: "Thanks for the detailed proposal. I'd like to discuss the fee structure before signing. Can we schedule a call this week?", sender_name: "Sarah Thompson", time: "2 hours ago" },
      { id: "m1c", direction: "out" as const, body: "Of course — happy to walk through the numbers. Are you free Thursday afternoon? We can also discuss any adjustments to the package.", sender_name: "Braxton OS Team", time: "1 hour ago" },
    ],
  },
  {
    id: "demo-thread-2",
    platform: "whatsapp",
    contact_name: "James Hartley",
    contact_id: "demo-contact-4",
    subject: "Maintenance Unit 3B — Boiler",
    status: "open",
    priority: "urgent",
    is_read: false,
    created_at: "2025-05-27T07:45:00Z",
    ai_summary: "James reports a recurring boiler issue at Unit 3B. Tenant has complained twice. Requires urgent engineer booking.",
    ai_next_action: "Book M&E engineer for Unit 3B this week. Notify tenant of appointment window. Update project tracker.",
    messages: [
      { id: "m2a", direction: "in" as const, body: "Hi, boiler's playing up again at 3B. Tenant's complained twice. Can you get someone out this week?", sender_name: "James Hartley", time: "6 hours ago" },
      { id: "m2b", direction: "out" as const, body: "On it James — I'll get M&E Contractors booked in. Will send you confirmation and keep the tenant updated.", sender_name: "Braxton OS Team", time: "5 hours ago" },
    ],
  },
  {
    id: "demo-thread-3",
    platform: "email",
    contact_name: "Marcus Webb",
    contact_id: "demo-contact-2",
    subject: "Investment follow-up — Salford opportunity",
    status: "waiting",
    priority: "high",
    is_read: true,
    created_at: "2025-05-26T16:00:00Z",
    ai_summary: "Marcus is interested in the Salford deal. Wants projected yield after fees — move to negotiation stage.",
    ai_next_action: "Send Salford yield breakdown document. Follow up if no response within 48 hours.",
    messages: [
      { id: "m3a", direction: "out" as const, body: "Marcus, following up on the investment pack. The Salford opportunity has 7.2% gross yield — happy to share the full breakdown.", sender_name: "Braxton OS Team", time: "2 days ago" },
      { id: "m3b", direction: "in" as const, body: "Appreciate you sending the deal pack. The Salford opportunity looks interesting — what's the projected yield after fees?", sender_name: "Marcus Webb", time: "1 day ago" },
    ],
  },
  {
    id: "demo-thread-4",
    platform: "website_form",
    contact_name: "Anonymous Lead",
    contact_id: null,
    subject: "Enquiry about property management",
    status: "open",
    priority: "normal",
    is_read: false,
    created_at: "2025-05-27T06:30:00Z",
    ai_summary: "New inbound enquiry via website form. Potential landlord with 2 properties looking for management service. Not yet in CRM.",
    ai_next_action: "Qualify lead and add to CRM. Reply within 1 hour for best conversion rate.",
    messages: [
      { id: "m4a", direction: "in" as const, body: "Hi, I have 2 rental properties in Leeds and I'm looking for a property management company. Do you cover the Leeds area? What are your management fees?", sender_name: "Website Visitor", time: "45 minutes ago" },
    ],
  },
  {
    id: "demo-thread-5",
    platform: "instagram",
    contact_name: "Priya Patel",
    contact_id: "demo-contact-3",
    subject: "Instagram DM — property management enquiry",
    status: "open",
    priority: "normal",
    is_read: true,
    created_at: "2025-05-23T14:00:00Z",
    ai_summary: "Priya responded to Instagram outreach. Has 2 single-lets in Birmingham. Interest is warm — needs nurturing.",
    ai_next_action: "Share case study or testimonial to build trust. Invite to a discovery call.",
    messages: [
      { id: "m5a", direction: "out" as const, body: "Hi Priya! We help landlords in Birmingham manage their portfolios without the hassle. Interested in learning how we could help with your properties?", sender_name: "Braxton OS", time: "1 week ago" },
      { id: "m5b", direction: "in" as const, body: "Hi, yes I do have 2 properties in Brum. I've been managing them myself but it's getting too much. What does your service include?", sender_name: "Priya Patel", time: "4 days ago" },
    ],
  },
  {
    id: "demo-thread-6",
    platform: "whatsapp",
    contact_name: "Daniel Osei",
    contact_id: "demo-contact-6",
    subject: "New build sourcing — London / West Midlands",
    status: "open",
    priority: "high",
    is_read: false,
    created_at: "2025-05-26T10:00:00Z",
    ai_summary: "Daniel reached out about sourcing new build opportunities. Budget appears substantial. Needs discovery call to qualify properly.",
    ai_next_action: "Book discovery call to discuss location criteria and deal structure. Add to CRM pipeline.",
    messages: [
      { id: "m6a", direction: "in" as const, body: "Hi, I'm looking to invest in new build properties — London or West Midlands. I saw your LinkedIn post about sourcing deals. Can we talk?", sender_name: "Daniel Osei", time: "Yesterday" },
      { id: "m6b", direction: "out" as const, body: "Hi Daniel, great to hear from you! We specialise in off-market new build deals in exactly those areas. When are you free for a 20-min call to discuss your criteria?", sender_name: "Braxton OS Team", time: "Yesterday" },
    ],
  },
];

export const DEMO_INBOX = [
  {
    id: "demo-conv-1",
    platform: "email",
    contact_name: "Sarah Thompson",
    subject: "Re: HMO management proposal",
    latest_message: "Thanks for the detailed proposal. I'd like to discuss the fee structure before signing. Can we schedule a call this week?",
    status: "open",
    priority: "high",
    is_read: false,
    created_at: "2025-05-27T09:15:00Z",
  },
  {
    id: "demo-conv-2",
    platform: "whatsapp",
    contact_name: "James Hartley",
    subject: "Maintenance request — Unit 3B",
    latest_message: "Hi, boiler's playing up again at 3B. Tenant's complained twice. Can you get someone out this week?",
    status: "open",
    priority: "urgent",
    is_read: false,
    created_at: "2025-05-27T07:45:00Z",
  },
  {
    id: "demo-conv-3",
    platform: "email",
    contact_name: "Marcus Webb",
    subject: "Investment opportunity follow-up",
    latest_message: "Appreciate you sending the deal pack. The Salford opportunity looks interesting — what's the projected yield after fees?",
    status: "waiting",
    priority: "high",
    is_read: true,
    created_at: "2025-05-26T16:00:00Z",
  },
];

export const DEMO_OUTREACH_CAMPAIGNS = [
  {
    id: "demo-campaign-1",
    name: "HMO Landlord Reactivation",
    goal: "Re-engage landlords who enquired but didn't convert",
    platform: "email",
    target_audience: "Landlords with 2+ properties who enquired in last 6 months",
    funnel_stage: "awareness",
    angle: "Case study: how we saved one landlord 12 hours/week",
    status: "active" as const,
    sent: 142,
    replies: 18,
    booked_calls: 3,
    revenue_attributed: "£0 (pipeline: £42k)",
    start_date: "2025-05-01",
  },
  {
    id: "demo-campaign-2",
    name: "Property Investor Pack",
    goal: "Nurture investors and move to discovery call",
    platform: "linkedin",
    target_audience: "Property investors with £200k+ available capital",
    funnel_stage: "nurture",
    angle: "Off-market deal access + sourcing expertise",
    status: "active" as const,
    sent: 87,
    replies: 24,
    booked_calls: 6,
    revenue_attributed: "£500k pipeline",
    start_date: "2025-04-15",
  },
  {
    id: "demo-campaign-3",
    name: "AI Automation for Property",
    goal: "Generate leads for AI automation service",
    platform: "instagram",
    target_audience: "Property operations managers and small agency owners",
    funnel_stage: "conversion",
    angle: "Stop doing manually what AI can do for you",
    status: "completed" as const,
    sent: 210,
    replies: 31,
    booked_calls: 2,
    revenue_attributed: "2 discovery calls booked",
    start_date: "2025-03-01",
  },
  {
    id: "demo-campaign-4",
    name: "Maintenance Client Upsell",
    goal: "Upsell existing maintenance clients to full management",
    platform: "whatsapp",
    target_audience: "Existing maintenance contract clients",
    funnel_stage: "upsell",
    angle: "Already trust us with your maintenance — let us handle everything",
    status: "completed" as const,
    sent: 34,
    replies: 14,
    booked_calls: 4,
    revenue_attributed: "£24,000 won",
    start_date: "2025-02-01",
  },
];

export const DEMO_CALENDAR_EVENTS = [
  {
    id: "demo-cal-1",
    title: "Thompson HMO — Fee Discussion Call",
    type: "call" as const,
    date: "2025-05-28",
    time: "14:00",
    duration_mins: 30,
    contact_name: "Sarah Thompson",
    contact_id: "demo-contact-1",
    location: "Zoom",
    notes: "Discuss revised fee structure. Sarah wants £1,400/mo vs our £1,500 proposal.",
    outcome: null,
    status: "upcoming" as const,
  },
  {
    id: "demo-cal-2",
    title: "Unit 3B — Boiler Engineer Site Visit",
    type: "site_visit" as const,
    date: "2025-05-29",
    time: "10:00",
    duration_mins: 120,
    contact_name: "James Hartley",
    contact_id: "demo-contact-4",
    location: "Unit 3B, Manchester",
    notes: "M&E Contractors attending. Possible full boiler replacement.",
    outcome: null,
    status: "upcoming" as const,
  },
  {
    id: "demo-cal-3",
    title: "Osei Group — New Build Discovery Call",
    type: "call" as const,
    date: "2025-05-30",
    time: "11:00",
    duration_mins: 30,
    contact_name: "Daniel Osei",
    contact_id: "demo-contact-6",
    location: "Google Meet",
    notes: "Qualify location criteria and budget. First call — bring London and WM deal examples.",
    outcome: null,
    status: "upcoming" as const,
  },
  {
    id: "demo-cal-4",
    title: "Monthly finance review",
    type: "meeting" as const,
    date: "2025-05-30",
    time: "16:00",
    duration_mins: 60,
    contact_name: "Internal",
    contact_id: null,
    location: "Office",
    notes: "Review May P&L, subscriptions, and cash position.",
    outcome: null,
    status: "upcoming" as const,
  },
  {
    id: "demo-cal-5",
    title: "FutureStack AI Demo Call",
    type: "call" as const,
    date: "2025-06-02",
    time: "10:30",
    duration_mins: 45,
    contact_name: "Olivia Chen",
    contact_id: "demo-contact-5",
    location: "Zoom",
    notes: "AI workflow discovery call. Olivia booked via Instagram campaign.",
    outcome: null,
    status: "upcoming" as const,
  },
  {
    id: "demo-cal-6",
    title: "Webb Investment — Negotiation Meeting",
    type: "meeting" as const,
    date: "2025-06-03",
    time: "14:00",
    duration_mins: 60,
    contact_name: "Marcus Webb",
    contact_id: "demo-contact-2",
    location: "London Office",
    notes: "Bring Salford deal pack and commission structure options.",
    outcome: null,
    status: "upcoming" as const,
  },
  {
    id: "demo-cal-7",
    title: "Patel Estates — Site Visit Birmingham",
    type: "site_visit" as const,
    date: "2025-05-22",
    time: "11:00",
    duration_mins: 90,
    contact_name: "Priya Patel",
    contact_id: "demo-contact-3",
    location: "Birmingham, B12",
    notes: "Viewed 2 single-let properties. Good condition. Priya interested but not committed.",
    outcome: "Properties inspected — follow up with management proposal this week",
    status: "completed" as const,
  },
  {
    id: "demo-cal-8",
    title: "Hartley Refurb — Phase 2 Deadline",
    type: "deadline" as const,
    date: "2025-06-01",
    time: "17:00",
    duration_mins: 0,
    contact_name: "James Hartley",
    contact_id: "demo-contact-4",
    location: null,
    notes: "Phase 2 completion deadline — bathroom retile and plastering must be signed off.",
    outcome: null,
    status: "upcoming" as const,
  },
];

export const DEMO_ACTIVITY_TIMELINE = [
  { id: "act-1",  type: "new_lead",         icon: "👤", label: "New lead captured",            detail: "Anonymous website enquiry — Leeds landlord with 2 properties",  time: "45 min ago",  category: "crm"      },
  { id: "act-2",  type: "message_received",  icon: "💬", label: "WhatsApp from James Hartley",  detail: "Boiler issue at Unit 3B — needs urgent engineer",                 time: "6 hrs ago",   category: "inbox"    },
  { id: "act-3",  type: "ai_scored",         icon: "⚡", label: "AI scored Sarah Thompson hot", detail: "Opened proposal 3x — high engagement signal",                    time: "2 hrs ago",   category: "crm"      },
  { id: "act-4",  type: "task_created",      icon: "✅", label: "Task auto-created",             detail: "Follow up Sarah Thompson on HMO proposal — due today",           time: "2 hrs ago",   category: "tasks"    },
  { id: "act-5",  type: "message_received",  icon: "✉️", label: "Email from Sarah Thompson",    detail: "Replied to proposal — wants to discuss fees",                    time: "2 hrs ago",   category: "inbox"    },
  { id: "act-6",  type: "payment_received",  icon: "💰", label: "Payment received",              detail: "James Hartley — £2,000 monthly maintenance contract",            time: "5 days ago",  category: "finance"  },
  { id: "act-7",  type: "deal_updated",      icon: "📈", label: "Deal moved to negotiation",    detail: "Webb Investment Acquisition — stage updated",                    time: "3 days ago",  category: "deals"    },
  { id: "act-8",  type: "call_booked",       icon: "📅", label: "Discovery call booked",         detail: "FutureStack Tech — Olivia Chen via Instagram campaign",          time: "3 days ago",  category: "calendar" },
  { id: "act-9",  type: "proposal_sent",     icon: "📄", label: "Proposal sent",                 detail: "Thompson HMO Portfolio — 4 HMOs at £1,500/mo",                  time: "5 days ago",  category: "deals"    },
  { id: "act-10", type: "automation_fired",  icon: "⚡", label: "Automation triggered",          detail: "n8n: Deal stage changed → Slack notification sent to team",     time: "3 days ago",  category: "system"   },
  { id: "act-11", type: "file_uploaded",     icon: "📁", label: "File uploaded",                 detail: "Hartley Refurb Phase 2 — contractor invoice uploaded",           time: "1 week ago",  category: "projects" },
  { id: "act-12", type: "new_lead",          icon: "👤", label: "4 new leads from LinkedIn",     detail: "LinkedIn campaign: Property Investor Pack — 4 responses",       time: "4 days ago",  category: "crm"      },
];

export const DEMO_TASKS = [
  {
    id: "demo-task-1",
    title: "Follow up Sarah Thompson on HMO proposal",
    task_type: "follow_up",
    status: "overdue",
    priority: "high",
    due_date: "2025-05-23",
    related_contact: "Sarah Thompson",
    related_project: "Thompson HMO Portfolio",
  },
  {
    id: "demo-task-2",
    title: "Send investment pack to Marcus Webb",
    task_type: "admin",
    status: "overdue",
    priority: "high",
    due_date: "2025-05-24",
    related_contact: "Marcus Webb",
    related_project: "Webb Investment Acquisition",
  },
  {
    id: "demo-task-3",
    title: "Book engineer for Unit 3B boiler",
    task_type: "maintenance",
    status: "todo",
    priority: "urgent",
    due_date: "2025-05-28",
    related_contact: "James Hartley",
    related_project: "Hartley Refurb — Unit 3B",
  },
  {
    id: "demo-task-4",
    title: "Schedule site visit — Patel Estates Birmingham",
    task_type: "meeting",
    status: "todo",
    priority: "medium",
    due_date: "2025-05-30",
    related_contact: "Priya Patel",
    related_project: null,
  },
  {
    id: "demo-task-5",
    title: "AI automation discovery call — FutureStack Tech",
    task_type: "call",
    status: "todo",
    priority: "urgent",
    due_date: "2025-06-02",
    related_contact: "Olivia Chen",
    related_project: null,
  },
  {
    id: "demo-task-6",
    title: "Monthly maintenance report — Hartley Build",
    task_type: "admin",
    status: "completed",
    priority: "low",
    due_date: "2025-05-20",
    related_contact: "James Hartley",
    related_project: "Hartley Refurb — Unit 3B",
  },
  {
    id: "demo-task-7",
    title: "Send Osei Group — discovery call agenda",
    task_type: "admin",
    status: "in_progress",
    priority: "medium",
    due_date: "2025-05-29",
    related_contact: "Daniel Osei",
    related_project: "Osei Group — New Build Sourcing",
  },
];

export const DEMO_WEEKLY_BRIEFING = {
  week: "19–25 May 2025",
  leads_this_week: 4,
  tasks_completed: 8,
  tasks_overdue: 3,
  revenue_this_week: "£12,400",
  expenses_this_week: "£3,200",
  ai_insight: "Sarah Thompson is showing high buying signals — she opened the proposal 3 times this week. Recommend following up within 24 hours with a revised fee structure.",
  recommended_focus: "Close Thompson HMO Portfolio this week. Pipeline value at risk if delayed past end of month.",
  weekly_goal: "Close 1 deal, qualify 2 new leads, clear overdue tasks",
  highlights: [
    "Marcus Webb replied to investment pack — move to negotiation",
    "FutureStack Tech booked AI discovery call",
    "Hartley refurb project 65% complete — on track",
    "4 new leads entered CRM from LinkedIn campaign",
  ],
};

export const DEMO_KPI = {
  active_leads:     12,
  open_deals:       5,
  total_pipeline:   "£742,000",
  tasks_due_today:  3,
  inbox_unread:     7,
  monthly_revenue:  "£38,400",
  conversion_rate:  "34%",
  avg_deal_days:    22,
  weekly_goal_pct:  68,
};

export const DEMO_AUTOMATION_FEED = [
  { event: "new_contact",       label: "New lead captured",              time: "2 min ago",  status: "success" },
  { event: "hot_lead",          label: "AI scored hot lead",             time: "14 min ago", status: "success" },
  { event: "task_created",      label: "Follow-up task auto-created",    time: "1 hr ago",   status: "success" },
  { event: "message_received",  label: "Inbox message routed",           time: "3 hr ago",   status: "success" },
  { event: "deal_updated",      label: "Deal stage updated",             time: "Yesterday",  status: "success" },
];

export const DEMO_PACKAGES = [
  {
    id: "starter",
    name: "Starter OS",
    price: "£997",
    period: "one-time setup + £197/mo",
    description: "For solo founders and small teams who need CRM, inbox, tasks and full visibility in one place.",
    features: [
      "CRM for up to 50 contacts",
      "Task & calendar management",
      "Inbox (email + WhatsApp)",
      "Basic automation (5 workflows)",
      "1 onboarding session",
    ],
    highlight: false,
  },
  {
    id: "growth",
    name: "Growth OS",
    price: "£2,497",
    period: "one-time setup + £397/mo",
    description: "For growing teams who need outreach, reporting, finance tracking and better operations.",
    features: [
      "Everything in Starter",
      "Unlimited CRM contacts",
      "Deal tracker + pipeline",
      "Advanced automations (25 workflows)",
      "Finance & project management",
      "Priority support",
    ],
    highlight: true,
  },
  {
    id: "automation",
    name: "Automation OS",
    price: "£4,997",
    period: "one-time setup + £697/mo",
    description: "For businesses ready for AI workflows, automated lead routing, and system integrations.",
    features: [
      "Everything in Growth",
      "AI lead qualification",
      "n8n workflow builder",
      "Custom integrations (CRMs, portals)",
      "White-label option",
      "Dedicated account manager",
    ],
    highlight: false,
  },
  {
    id: "custom",
    name: "Custom AI OS",
    price: "From £9,997",
    period: "bespoke pricing",
    description: "For operations-heavy businesses needing a fully bespoke system with custom dashboards and advanced integrations.",
    features: [
      "Everything in Automation",
      "Custom AI models & prompts",
      "Bespoke workflow design",
      "API & data integrations",
      "Staff training & rollout",
      "Ongoing development retainer",
    ],
    highlight: false,
  },
];
